### ISSUE TITLE
A problem occurred configuring project ':tp-react-native-bluetooth-escpos-printer'.

### ISSUE THREAD

**Issue by pravin190786** [tulparyazilim/tp-react-native-bluetooth-printer#6]
* What went wrong:
A problem occurred configuring project ':tp-react-native-bluetooth-escpos-printer'.
> Could not determine the dependencies of null.
   > Could not resolve all dependencies for configuration ':tp-react-native-bluetooth-escpos-printer:classpath'.
      > Using insecure protocols with repositories, without explicit opt-in, is unsupported. Switch Maven repository 'BintrayJCenter(http://jcenter.bintray.com/)' to redirect to a secure protocol (like HTTPS) or allow insecure protocols. See https://docs.gradle.org/7.5.1/dsl/org.gradle.api.artifacts.repositories.UrlArtifactRepository.html#org.gradle.api.artifacts.repositories.UrlArtifactRepository:allowInsecureProtocol for more details.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 11s

    at makeError (C:\ReactNativeExamples\printImgTejas\node_modules\@react-native-community\cli-platform-android\node_modules\execa\index.js:174:9)
    at C:\ReactNativeExamples\printImgTejas\node_modules\@react-native-community\cli-platform-android\node_modules\execa\index.js:278:16
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async runOnAllDevices (C:\ReactNativeExamples\printImgTejas\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:109:5)
    at async Command.handleAction (C:\ReactNativeExamples\printImgTejas\node_modules\@react-native-community\cli\build\index.js:192:9)
info Run CLI with --verbose flag for more details.

**Comment by khairul169** [comment]
Pull request #7 will fix this issue. cc @tulparyazilim
